-- シードデータ: master_cards テーブルに価値観ワード 50 枚を投入する。
-- スペース作成時に master_cards から cards テーブルへコピーして使用する。
--
-- 実行方法:
--   pnpm db:seed

INSERT OR IGNORE INTO master_cards (id, text, is_active, created_at, updated_at) VALUES
  ('mc-001', '誠実さ',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-002', '創造性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-003', 'チームワーク', 1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-004', '挑戦',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-005', '成長',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-006', '貢献',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-007', '信頼',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-008', '自由',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-009', '責任',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-010', '革新',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-011', '共感',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-012', '効率',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-013', '情熱',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-014', '誠意',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-015', '公平',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-016', '謙虚さ',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-017', '勇気',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-018', '感謝',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-019', '継続',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-020', '品質',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-021', '多様性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-022', '協調',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-023', '独創性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-024', '決断力',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-025', '柔軟性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-026', '透明性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-027', '向上心',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-028', '思いやり',   1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-029', '正直さ',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-030', '探求心',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-031', '包容力',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-032', '実行力',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-033', '丁寧さ',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-034', '開放性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-035', '献身',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-036', '楽観性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-037', '集中力',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-038', '自律',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-039', '調和',       1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-040', '粘り強さ',   1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-041', 'ユーモア',   1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-042', '論理性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-043', '先見性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-044', '親切さ',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-045', '積極性',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-046', '冷静さ',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-047', '倫理観',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-048', '行動力',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-049', '連帯感',     1, strftime('%s', 'now'), strftime('%s', 'now')),
  ('mc-050', '夢',         1, strftime('%s', 'now'), strftime('%s', 'now'));
